openapi: 3.0.1
info:
  version: 1.0.0
  title: Notification Aggregator

x-amazon-apigateway-request-validators:
  default:
    validateRequestBody: true
    validateRequestParameters: true

x-amazon-apigateway-request-validator: default

paths:
  /notifications/{post-id}:
    parameters:
      - $ref: '#/components/parameters/post-id'
    get:
      responses:
        '200':
          description: 'Get all notifications'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notifications'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetNotificationsLambda.Arn}/invocations"
    post:
      description: 'Create a notification'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNotification'
      responses:
        '201':
          description: 'Notification created'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateNotificationLambda.Arn}/invocations"

  /notifications/{post-id}/{notification-id}/read:
    parameters:
      - $ref: '#/components/parameters/post-id'
      - $ref: '#/components/parameters/notification-id'
    put:
      responses:
        '202':
          description: 'Mark notification as read for a post'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MarkNotificationLambda.Arn}/invocations"

components:
  schemas:
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    CreateNotification:
      type: object
      required:
        - type
        - postTitle
        - user
      properties:
        type:
          type: string
          enum:
            - 'Like'
            - 'Comment'
        postTitle:
            type: string
            minLength: 1
        user:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: string
              minLength: 1
            name:
              type: string
              minLength: 1
        comment:
          type: object
          required:
            - id
            - commentText
          properties:
            id:
              type: string
              minLength: 1
            commentText:
              type: string
              minLength: 1
    NotificationResponse:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        read:
          type: boolean
        post:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
        user:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
        comment:
          type: object
          properties:
            id:
              type: string
            commentText:
              type: string
    Notifications:
      type: array
      items:
        $ref: '#/components/schemas/NotificationResponse'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    post-id:
        in: path
        name: post-id
        required: true
        schema:
          type: string
    notification-id:
      in: path
      name: notification-id
      required: true
      schema:
        type: string

